name: Github By susmitha
run-name: ${{ github.actor }} is running the Github Actions 
## This will run either on push, pull_request

on: [push, pull_request]

jobs:
  build-and-deploy: ## Name of the job
    runs-on: ubuntu-latest ## Github Hosed [Self Hosted]
    steps:
       - name: "Printing message"
         run: echo "my First job"
       - name: Checkout Code
         uses: actions/checkout@v4.1.7
         with:
           fetch-depth: 0
       - name: check
         run: echo "Test"
       - name: Install npm
         run: npm install
       - name: Install Salesforce CLI
         run: npm install @salesforce/cli --global
       - name: Encrypt the server.key file using the below command
         run: openssl enc -nosalt -aes-256-cbc -in assets/dev/server.key -out assets/dev/server.key.enc -k B3F5D970BC2CE63508454E2CD9C8A48CB516F0EBC797AE87E6183F12827A6074 -iv 6104B8F9B7603076DB0A5CB77E8C823B
       - name: Authorize with Salesforce Org
         run: sf org login jwt --username sumatt1617-8tnr@force.com.dev --jwt-key-file assets/dev/server.key --client-id 3MVG9duA.sPEm7m8bEEHD0tEdO3cfTZ.zckjO5.w8y8ag74VunrNYWOkXOvRDYHsXvn1Ef0tp6lEb2IFuzHaM --alias dev --set-default --instance-url https://test.salesforce.com
       - name: print user Information
         run: sf org display user -o dev     
    
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ths is a second job"
        name: "Printing message"